language: node_js
node_js:
    - "0.10"

before_install:
    - npm install eslint
    - sudo apt-get update -qq
    - sudo apt-get install -y gettext libglib2.0-dev libxml2-dev swig pkg-config gtk-doc-tools gobject-introspection automake make
    - wget http://www.vips.ecs.soton.ac.uk/supported/current/vips-7.38.5.tar.gz -O /tmp/vips-7.38.5.tar.gz
    - cd /tmp/ && tar -xzvf /tmp/vips-7.38.5.tar.gz
    - cd /tmp/vips-7.38.5 && ./configure && make && sudo make install
    - cd /home/travis/build/MaliceLabs/phoenix/

script:
    - node node_modules/eslint/bin/eslint.js .
