language: node_js
node_js:
    - "0.10"

before_install:
    - npm install eslint
    - sudo apt-get update -qq
    - sudo apt-get install -y libvips-dev

script:
    - node node_modules/eslint/bin/eslint.js .
